# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Theme Settings
remote_theme            : "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin   : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site settings
title                   : RefaceCPLiveControl
subtitle                : "Ableton Live script for the Yamaha Reface CP"
name                    : &name "Joan Duat" # &name is a YAML anchor which can be *referenced later
description             : >- # this means to ignore newlines until "baseurl:"
  RefaceCPLiveControl is an Ableton Live Control Surface script for the Yamaha Reface CP keyboard.
url                     : https://yannxou.github.io # the base hostname & protocol for your site
baseurl                 : "/RefaceCPLiveControl" # the subpath of your site, e.g. "/blog"
repository              : "yannxou/RefaceCPLiveControl"
twitter_username        : yannxou
github_username         : yannxou
enable_copy_code_button : true
atom_feed:
  hide                  : true

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "GTM-NLDW5Z99" # Replace this with your ID, or delete
    anonymize_ip         : true

# Site Author
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "/assets/images/yannxou.jpg"
  bio              : "iOS developer, music enthusiast and occasional open-source contributor."
  location         : "Barcelona"
  links:
    - label: "X"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/yannxou"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yannxou"
    - label: "Soundcloud"
      icon: "fab fa-fw fa-soundcloud"
      url: "https://soundcloud.com/bachstripvoice"

# Site Footer
footer:
  links:
    - label: ""
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/yannxou"
    - label: ""
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yannxou"
    - label: ""
      icon: "fab fa-fw fa-soundcloud"
      url: "https://soundcloud.com/bachstripvoice"

# Reading Files
include:
  - _docs
  - _pages

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      toc_sticky: true
      sidebar:
        nav: "docs"
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Build settings

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

